package com.cjs.example.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ClientDetails
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Clientdetails implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ClientDetails.appId
     *
     * @mbg.generated
     */
    private String appid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ClientDetails.resourceIds
     *
     * @mbg.generated
     */
    private String resourceids;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ClientDetails.appSecret
     *
     * @mbg.generated
     */
    private String appsecret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ClientDetails.scope
     *
     * @mbg.generated
     */
    private String scope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ClientDetails.grantTypes
     *
     * @mbg.generated
     */
    private String granttypes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ClientDetails.redirectUrl
     *
     * @mbg.generated
     */
    private String redirecturl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ClientDetails.authorities
     *
     * @mbg.generated
     */
    private String authorities;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ClientDetails.access_token_validity
     *
     * @mbg.generated
     */
    private Integer accessTokenValidity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ClientDetails.refresh_token_validity
     *
     * @mbg.generated
     */
    private Integer refreshTokenValidity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ClientDetails.additionalInformation
     *
     * @mbg.generated
     */
    private String additionalinformation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ClientDetails.autoApproveScopes
     *
     * @mbg.generated
     */
    private String autoapprovescopes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ClientDetails
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ClientDetails.appId
     *
     * @return the value of ClientDetails.appId
     *
     * @mbg.generated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ClientDetails.appId
     *
     * @param appid the value for ClientDetails.appId
     *
     * @mbg.generated
     */
    public void setAppid(String appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ClientDetails.resourceIds
     *
     * @return the value of ClientDetails.resourceIds
     *
     * @mbg.generated
     */
    public String getResourceids() {
        return resourceids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ClientDetails.resourceIds
     *
     * @param resourceids the value for ClientDetails.resourceIds
     *
     * @mbg.generated
     */
    public void setResourceids(String resourceids) {
        this.resourceids = resourceids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ClientDetails.appSecret
     *
     * @return the value of ClientDetails.appSecret
     *
     * @mbg.generated
     */
    public String getAppsecret() {
        return appsecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ClientDetails.appSecret
     *
     * @param appsecret the value for ClientDetails.appSecret
     *
     * @mbg.generated
     */
    public void setAppsecret(String appsecret) {
        this.appsecret = appsecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ClientDetails.scope
     *
     * @return the value of ClientDetails.scope
     *
     * @mbg.generated
     */
    public String getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ClientDetails.scope
     *
     * @param scope the value for ClientDetails.scope
     *
     * @mbg.generated
     */
    public void setScope(String scope) {
        this.scope = scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ClientDetails.grantTypes
     *
     * @return the value of ClientDetails.grantTypes
     *
     * @mbg.generated
     */
    public String getGranttypes() {
        return granttypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ClientDetails.grantTypes
     *
     * @param granttypes the value for ClientDetails.grantTypes
     *
     * @mbg.generated
     */
    public void setGranttypes(String granttypes) {
        this.granttypes = granttypes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ClientDetails.redirectUrl
     *
     * @return the value of ClientDetails.redirectUrl
     *
     * @mbg.generated
     */
    public String getRedirecturl() {
        return redirecturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ClientDetails.redirectUrl
     *
     * @param redirecturl the value for ClientDetails.redirectUrl
     *
     * @mbg.generated
     */
    public void setRedirecturl(String redirecturl) {
        this.redirecturl = redirecturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ClientDetails.authorities
     *
     * @return the value of ClientDetails.authorities
     *
     * @mbg.generated
     */
    public String getAuthorities() {
        return authorities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ClientDetails.authorities
     *
     * @param authorities the value for ClientDetails.authorities
     *
     * @mbg.generated
     */
    public void setAuthorities(String authorities) {
        this.authorities = authorities;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ClientDetails.access_token_validity
     *
     * @return the value of ClientDetails.access_token_validity
     *
     * @mbg.generated
     */
    public Integer getAccessTokenValidity() {
        return accessTokenValidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ClientDetails.access_token_validity
     *
     * @param accessTokenValidity the value for ClientDetails.access_token_validity
     *
     * @mbg.generated
     */
    public void setAccessTokenValidity(Integer accessTokenValidity) {
        this.accessTokenValidity = accessTokenValidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ClientDetails.refresh_token_validity
     *
     * @return the value of ClientDetails.refresh_token_validity
     *
     * @mbg.generated
     */
    public Integer getRefreshTokenValidity() {
        return refreshTokenValidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ClientDetails.refresh_token_validity
     *
     * @param refreshTokenValidity the value for ClientDetails.refresh_token_validity
     *
     * @mbg.generated
     */
    public void setRefreshTokenValidity(Integer refreshTokenValidity) {
        this.refreshTokenValidity = refreshTokenValidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ClientDetails.additionalInformation
     *
     * @return the value of ClientDetails.additionalInformation
     *
     * @mbg.generated
     */
    public String getAdditionalinformation() {
        return additionalinformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ClientDetails.additionalInformation
     *
     * @param additionalinformation the value for ClientDetails.additionalInformation
     *
     * @mbg.generated
     */
    public void setAdditionalinformation(String additionalinformation) {
        this.additionalinformation = additionalinformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ClientDetails.autoApproveScopes
     *
     * @return the value of ClientDetails.autoApproveScopes
     *
     * @mbg.generated
     */
    public String getAutoapprovescopes() {
        return autoapprovescopes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ClientDetails.autoApproveScopes
     *
     * @param autoapprovescopes the value for ClientDetails.autoApproveScopes
     *
     * @mbg.generated
     */
    public void setAutoapprovescopes(String autoapprovescopes) {
        this.autoapprovescopes = autoapprovescopes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientDetails
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", appid=").append(appid);
        sb.append(", resourceids=").append(resourceids);
        sb.append(", appsecret=").append(appsecret);
        sb.append(", scope=").append(scope);
        sb.append(", granttypes=").append(granttypes);
        sb.append(", redirecturl=").append(redirecturl);
        sb.append(", authorities=").append(authorities);
        sb.append(", accessTokenValidity=").append(accessTokenValidity);
        sb.append(", refreshTokenValidity=").append(refreshTokenValidity);
        sb.append(", additionalinformation=").append(additionalinformation);
        sb.append(", autoapprovescopes=").append(autoapprovescopes);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientDetails
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Clientdetails other = (Clientdetails) that;
        return (this.getAppid() == null ? other.getAppid() == null : this.getAppid().equals(other.getAppid()))
            && (this.getResourceids() == null ? other.getResourceids() == null : this.getResourceids().equals(other.getResourceids()))
            && (this.getAppsecret() == null ? other.getAppsecret() == null : this.getAppsecret().equals(other.getAppsecret()))
            && (this.getScope() == null ? other.getScope() == null : this.getScope().equals(other.getScope()))
            && (this.getGranttypes() == null ? other.getGranttypes() == null : this.getGranttypes().equals(other.getGranttypes()))
            && (this.getRedirecturl() == null ? other.getRedirecturl() == null : this.getRedirecturl().equals(other.getRedirecturl()))
            && (this.getAuthorities() == null ? other.getAuthorities() == null : this.getAuthorities().equals(other.getAuthorities()))
            && (this.getAccessTokenValidity() == null ? other.getAccessTokenValidity() == null : this.getAccessTokenValidity().equals(other.getAccessTokenValidity()))
            && (this.getRefreshTokenValidity() == null ? other.getRefreshTokenValidity() == null : this.getRefreshTokenValidity().equals(other.getRefreshTokenValidity()))
            && (this.getAdditionalinformation() == null ? other.getAdditionalinformation() == null : this.getAdditionalinformation().equals(other.getAdditionalinformation()))
            && (this.getAutoapprovescopes() == null ? other.getAutoapprovescopes() == null : this.getAutoapprovescopes().equals(other.getAutoapprovescopes()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientDetails
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getAppid() == null) ? 0 : getAppid().hashCode());
        result = prime * result + ((getResourceids() == null) ? 0 : getResourceids().hashCode());
        result = prime * result + ((getAppsecret() == null) ? 0 : getAppsecret().hashCode());
        result = prime * result + ((getScope() == null) ? 0 : getScope().hashCode());
        result = prime * result + ((getGranttypes() == null) ? 0 : getGranttypes().hashCode());
        result = prime * result + ((getRedirecturl() == null) ? 0 : getRedirecturl().hashCode());
        result = prime * result + ((getAuthorities() == null) ? 0 : getAuthorities().hashCode());
        result = prime * result + ((getAccessTokenValidity() == null) ? 0 : getAccessTokenValidity().hashCode());
        result = prime * result + ((getRefreshTokenValidity() == null) ? 0 : getRefreshTokenValidity().hashCode());
        result = prime * result + ((getAdditionalinformation() == null) ? 0 : getAdditionalinformation().hashCode());
        result = prime * result + ((getAutoapprovescopes() == null) ? 0 : getAutoapprovescopes().hashCode());
        return result;
    }
}