package com.cjs.example.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table oauth_approvals
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class OauthApprovals implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_approvals.userId
     *
     * @mbg.generated
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_approvals.clientId
     *
     * @mbg.generated
     */
    private String clientid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_approvals.scope
     *
     * @mbg.generated
     */
    private String scope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_approvals.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_approvals.expiresAt
     *
     * @mbg.generated
     */
    private Integer expiresat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oauth_approvals.lastModifiedAt
     *
     * @mbg.generated
     */
    private Integer lastmodifiedat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table oauth_approvals
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_approvals.userId
     *
     * @return the value of oauth_approvals.userId
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_approvals.userId
     *
     * @param userid the value for oauth_approvals.userId
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_approvals.clientId
     *
     * @return the value of oauth_approvals.clientId
     *
     * @mbg.generated
     */
    public String getClientid() {
        return clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_approvals.clientId
     *
     * @param clientid the value for oauth_approvals.clientId
     *
     * @mbg.generated
     */
    public void setClientid(String clientid) {
        this.clientid = clientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_approvals.scope
     *
     * @return the value of oauth_approvals.scope
     *
     * @mbg.generated
     */
    public String getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_approvals.scope
     *
     * @param scope the value for oauth_approvals.scope
     *
     * @mbg.generated
     */
    public void setScope(String scope) {
        this.scope = scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_approvals.status
     *
     * @return the value of oauth_approvals.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_approvals.status
     *
     * @param status the value for oauth_approvals.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_approvals.expiresAt
     *
     * @return the value of oauth_approvals.expiresAt
     *
     * @mbg.generated
     */
    public Integer getExpiresat() {
        return expiresat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_approvals.expiresAt
     *
     * @param expiresat the value for oauth_approvals.expiresAt
     *
     * @mbg.generated
     */
    public void setExpiresat(Integer expiresat) {
        this.expiresat = expiresat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oauth_approvals.lastModifiedAt
     *
     * @return the value of oauth_approvals.lastModifiedAt
     *
     * @mbg.generated
     */
    public Integer getLastmodifiedat() {
        return lastmodifiedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oauth_approvals.lastModifiedAt
     *
     * @param lastmodifiedat the value for oauth_approvals.lastModifiedAt
     *
     * @mbg.generated
     */
    public void setLastmodifiedat(Integer lastmodifiedat) {
        this.lastmodifiedat = lastmodifiedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userid=").append(userid);
        sb.append(", clientid=").append(clientid);
        sb.append(", scope=").append(scope);
        sb.append(", status=").append(status);
        sb.append(", expiresat=").append(expiresat);
        sb.append(", lastmodifiedat=").append(lastmodifiedat);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OauthApprovals other = (OauthApprovals) that;
        return (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getClientid() == null ? other.getClientid() == null : this.getClientid().equals(other.getClientid()))
            && (this.getScope() == null ? other.getScope() == null : this.getScope().equals(other.getScope()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getExpiresat() == null ? other.getExpiresat() == null : this.getExpiresat().equals(other.getExpiresat()))
            && (this.getLastmodifiedat() == null ? other.getLastmodifiedat() == null : this.getLastmodifiedat().equals(other.getLastmodifiedat()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getClientid() == null) ? 0 : getClientid().hashCode());
        result = prime * result + ((getScope() == null) ? 0 : getScope().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getExpiresat() == null) ? 0 : getExpiresat().hashCode());
        result = prime * result + ((getLastmodifiedat() == null) ? 0 : getLastmodifiedat().hashCode());
        return result;
    }
}