package com.cjs.example.dao;

import com.cjs.example.entity.Clientdetails;
import com.cjs.example.entity.ClientdetailsQuery;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ClientdetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientDetails
     *
     * @mbg.generated
     */
    long countByExample(ClientdetailsQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientDetails
     *
     * @mbg.generated
     */
    int deleteByExample(ClientdetailsQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientDetails
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String appid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientDetails
     *
     * @mbg.generated
     */
    int insert(Clientdetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientDetails
     *
     * @mbg.generated
     */
    int insertSelective(Clientdetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientDetails
     *
     * @mbg.generated
     */
    List<Clientdetails> selectByExampleWithRowbounds(ClientdetailsQuery example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientDetails
     *
     * @mbg.generated
     */
    List<Clientdetails> selectByExample(ClientdetailsQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientDetails
     *
     * @mbg.generated
     */
    Clientdetails selectByPrimaryKey(String appid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientDetails
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Clientdetails record, @Param("example") ClientdetailsQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientDetails
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Clientdetails record, @Param("example") ClientdetailsQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientDetails
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Clientdetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ClientDetails
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Clientdetails record);
}