package com.cjs.example.dao;

import com.cjs.example.entity.OauthCode;
import com.cjs.example.entity.OauthCodeQuery;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OauthCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbg.generated
     */
    long countByExample(OauthCodeQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbg.generated
     */
    int deleteByExample(OauthCodeQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbg.generated
     */
    int insert(OauthCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbg.generated
     */
    int insertSelective(OauthCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbg.generated
     */
    List<OauthCode> selectByExampleWithBLOBsWithRowbounds(OauthCodeQuery example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbg.generated
     */
    List<OauthCode> selectByExampleWithBLOBs(OauthCodeQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbg.generated
     */
    List<OauthCode> selectByExampleWithRowbounds(OauthCodeQuery example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbg.generated
     */
    List<OauthCode> selectByExample(OauthCodeQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OauthCode record, @Param("example") OauthCodeQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") OauthCode record, @Param("example") OauthCodeQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_code
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OauthCode record, @Param("example") OauthCodeQuery example);
}