package com.cjs.example.dao;

import com.cjs.example.entity.OauthApprovals;
import com.cjs.example.entity.OauthApprovalsQuery;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface OauthApprovalsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbg.generated
     */
    long countByExample(OauthApprovalsQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbg.generated
     */
    int deleteByExample(OauthApprovalsQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbg.generated
     */
    int insert(OauthApprovals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbg.generated
     */
    int insertSelective(OauthApprovals record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbg.generated
     */
    List<OauthApprovals> selectByExampleWithRowbounds(OauthApprovalsQuery example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbg.generated
     */
    List<OauthApprovals> selectByExample(OauthApprovalsQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OauthApprovals record, @Param("example") OauthApprovalsQuery example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table oauth_approvals
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OauthApprovals record, @Param("example") OauthApprovalsQuery example);
}